version: 2

sources:
  - name: source
    database: dbt-tutorial-dev
    schema: source
    config:
      enabled: true
    tables:
      - name: dim_customer  # enabled
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_returns
      - name: fact_sales  # not enabled
        